"""empty message

Revision ID: 02b63e963116
Revises: 0bf0ded5e39c
Create Date: 2016-06-18 21:17:21.263327

"""

# revision identifiers, used by Alembic.
revision = '02b63e963116'
down_revision = '0bf0ded5e39c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('amount', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'amount')
    ### end Alembic commands ###
